### ISSUE TITLE
Allow JDFlipViewRelativeMargin to be configured

### ISSUE THREAD

**Issue by cyrilchandelier** [jaydee3/JDFlipNumberView#37]
This value should be configurable someplace in the component to enhance the rendering. 

For instance with my custom design, the views are too close one from each other, I would like to set JDFlipViewRelativeMargin to something like 30%.

**Comment by johnboiles** [comment]
:+1: agree. I might give this a shot.

Another way to think about it could be to add two values that work in points instead of percentages:

```objc
//! Outer padding in points
@property UIEdgeInsets insets;
//! Spacing between numbers in points
@property CGFloat numberMargin;
```

What do you think about that instead of doing a percentage margin?

**Comment by jaydee3** [comment]
We can make two properties:

  @property CGFloat relativeDigitMargin;
  @property CGFloat absoluteDigitMargin;

and then just use `MAX(relative*width, absolute)` as margin. Pull requests welcome.

**Comment by johnboiles** [comment]
Here you go! #42
